<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<SignAssembly>True</SignAssembly>
		<IsTestProject>true</IsTestProject>
		<AssemblyOriginatorKeyFile>ReadHeavyCollections.Tests.snk</AssemblyOriginatorKeyFile>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReadHeavyCollections\ReadHeavyCollections.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="xunit.runner.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
